### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by ClosetMonkey** [rondoni/webudp#1]
Do you have any example code? Very interested in this project as an alternative to seemk/WebUDP.

**Comment by ClosetMonkey** [comment]
Specifically looking for client javascript to use with existing test.

**Comment by rondoni** [comment]
kinda late, but i did add a simple test html+js

**Comment by ClosetMonkey** [comment]
I'll check it out

**Comment by ClosetMonkey** [comment]
Few things.
1. On Ubuntu 18 I had to add "-std=c++11" to Makefile as well as add `#include <stdint.h>` to a few files such as sctp.h . I'm presuming your GCC version is different than what is default on my machine.
2. Had to change cert and pkey to `char* cert` and `char* pkey` and use the full path to file. Don't know why, but the function `SSL_CTX_use_certificate_file` was failing until I did so.
3. I still haven't been able to successfully connect due to errors while setting up ICE according to chrome://webrtc-internals.

You're doing a great job though. Keep it up!

**Comment by rondoni** [comment]
I cloned it onto a virtual machine running ubuntu 18.04.2. No problems compiling the source. There was a small error in webudptest.cpp, which should be fixed now. The stdint stuff probably does have to do with a different version of gcc. 

The browser test should work as is with chrome. I just tried it with firefox, and I do get an ICE error, which is because firefox doesn't like localhost. You can fix this by changing the ipaddr in main.js to something else, like your public ip address, or your local address through router.

**Comment by ClosetMonkey** [comment]
./webudptest returns:
```
sending 64 bytes
sending 64 bytes
sending 1648 bytes
sending 1648 bytes
exited with state: -3
```
Monitoring webudptest/index.html via chrome://webrtc-internals shows the datachannel's connection state constantly at 'connecting' with iceconnectionstatechange reciving a 'failed' event after 30 seconds which I believe is a timeout from ./webudptest server crashing.

**Comment by rondoni** [comment]
The ~1600 bytes is the server server hello response for dtls handshake. I think it's crashing because the fingerprint value in main.js is for my certificate, not yours, so the handshake fails. 

try using this or some other tool to calculate the fingerprint for your cert:
https://www.samltool.com/fingerprint.php
